### PR TITLE
feat(time): parses default time.Duration via time.ParseDuration

### PR DESCRIPTION
**Pull request by russmatney**

### CODE REVIEW

**Comment by russmatney** [comment]
Love the tool, thanks much!

I needed a default duration today – this checks the type and uses `time.ParseDuration` to parse the value if it is a `time.Duration`.

Let me know if you want anything else, I'd be happy to spend more time with it.

**Comment by bc-vincent-zhao** [comment]
That's really neat addition, as duration is a very common fields people want to have default values for (various timeout). thanks for doing it @russmatney. I was going to do it as well until I see you've already opened an PR for it. 

@mcuadros would you please see if we can get this merged ?

**Comment by mcuadros** [comment]
Great addition, but will be great if you can build the feature using the a [map with functions by Type](https://github.com/mcuadros/go-defaults/blob/master/filler.go#L21), since this library is using a small framework (unpublished) for fill structs based on it, it covers more functionality, than just the go-defualts itself.

https://github.com/mcuadros/go-defaults/blob/master/filler_test.go#L43-L54

**Comment by russmatney** [comment]
@mcuadros @bc-vincent-zhao Thanks for the feedback – will take another crack at it, hopefully will have a moment sometime today.

**Comment by russmatney** [comment]
Sorry for the delay here – I tried to get this refactor done before my trip, but I wasn't able to – I'm going to be traveling for two weeks and won't be able to touch this until after then. @bc-vincent-zhao if there's a pressing need, go for it, otherwise I'll make time when I return.

**Pull request closed without merging**
